# Generated by Django 2.1.5 on 2020-06-02 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_task', '0002_task_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test_Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='用例名称')),
                ('failures', models.IntegerField(verbose_name='失败用例')),
                ('errors', models.IntegerField(verbose_name='错误用例')),
                ('skipped', models.IntegerField(verbose_name='跳过的用例')),
                ('tests', models.IntegerField(verbose_name='运行总用例数')),
                ('time', models.FloatField(verbose_name='运行总时长')),
                ('result', models.TextField(default='', verbose_name='详情')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_task.Task')),
            ],
        ),
    ]
