# Generated by Django 2.0.3 on 2020-07-24 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_task', '0004_auto_20200602_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='report',
            field=models.CharField(max_length=100, null=True, verbose_name='关联的测试报告'),
        ),
    ]
