# Generated by Django 2.1.5 on 2020-07-24 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_task', '0005_task_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testreport',
            name='task',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='TestReport',
        ),
    ]
