# Generated by Django 2.1.5 on 2020-07-24 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_task', '0006_auto_20200724_1218'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('describe', models.TextField(default='', verbose_name='描述')),
                ('cases', models.TextField(default='', verbose_name='关联用例')),
                ('status', models.SmallIntegerField(choices=[('0', '未执行'), ('1', '执行中'), ('2', '已完成')], default='0', verbose_name='状态')),
                ('report', models.CharField(max_length=100, null=True, verbose_name='关联的测试报告')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更改时间')),
            ],
        ),
    ]
