# Generated by Django 2.1.5 on 2020-06-03 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_variable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variable',
            name='key',
            field=models.CharField(max_length=255, null=True, verbose_name='键'),
        ),
        migrations.AlterField(
            model_name='variable',
            name='value',
            field=models.CharField(max_length=255, null=True, verbose_name='值'),
        ),
    ]
