# Generated by Django 2.1.5 on 2020-06-10 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_variable', '0004_variable_extract_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variable',
            name='api',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_api.ApiCase'),
        ),
    ]
