# Generated by Django 2.1.5 on 2020-04-30 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='接口名称')),
                ('url', models.CharField(max_length=500, verbose_name='url地址')),
                ('method', models.CharField(choices=[('POST', 'POST'), ('GET', 'GET'), ('PUT', 'PUT'), ('DELETE', 'DELETE')], default='GET', max_length=100, verbose_name='请求方式')),
                ('header', models.TextField(blank=True, null=True, verbose_name='请求头')),
                ('req_type', models.CharField(choices=[('FORM-DATA', 'FORM-DATA'), ('JSON', 'JSON')], default='FORM-DATA', max_length=50, verbose_name='参数类型')),
                ('req_body', models.TextField(blank=True, null=True, verbose_name='参数内容')),
                ('assert_type', models.CharField(choices=[('INCLUDE', 'INCLUDE'), ('EQUAL', 'EQUAL')], default='INCLUDE', max_length=50, verbose_name='断言类型')),
                ('assert_body', models.TextField(blank=True, null=True, verbose_name='断言内容')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_module.Module')),
            ],
            options={
                'db_table': 'apicase',
            },
        ),
    ]
