# Generated by Django 2.1.5 on 2020-06-08 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0003_apicase_response_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiCaseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[(1, '单接口用例'), (2, '多接口业务用例'), (3, '公共前置接口用例')], default=1, max_length=100, verbose_name='接口用例类型')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.AddField(
            model_name='apicase',
            name='api_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_api.ApiCaseType'),
            preserve_default=False,
        ),
    ]
