# Generated by Django 2.1.5 on 2020-06-09 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0004_auto_20200608_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='apicase',
            name='is_cookie',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='NO', max_length=50, verbose_name='是否获取cookie'),
        ),
    ]
